# Generated by Django 4.0.3 on 2022-04-06 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_included_dose_alter_included_dose_metrics_and_more'),
        ('survey', '0005_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestionchoices',
            name='related_ingrediant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ingrediant'),
        ),
    ]
