# Generated by Django 4.0.3 on 2022-04-06 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_surveyquestionchoices_related_ingrediant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestionchoices',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='survey.surveyquestion'),
        ),
    ]
