# Generated by Django 4.0.3 on 2022-04-06 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_ingrediant_dose_recomm_and_more'),
        ('survey', '0007_alter_surveyquestionchoices_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestionchoices',
            name='related_ingrediant',
        ),
        migrations.CreateModel(
            name='ChoicesIngrediant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_ingrediants', to='survey.surveyquestionchoices')),
                ('ingrediant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_choices', to='products.ingrediant')),
            ],
        ),
    ]
