# Generated by Django 4.0.3 on 2022-03-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
    ]
