# Generated by Django 4.0.3 on 2022-03-31 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_cart'),
        ('products', '0004_product_thumbnail_url'),
    ]

    operations = [
    ]
