# Generated by Django 4.0.3 on 2022-03-31 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_review_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='delivery_fee',
        ),
    ]
