# Generated by Django 4.0.3 on 2022-04-01 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_content'),
        ('products', '0007_remove_cart_delivery_fee'),
    ]

    operations = [
    ]
