# Generated by Django 4.0.3 on 2022-04-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_merge_20220401_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='included',
            name='dose',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='included',
            name='dose_metrics',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='ingrediant',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ingrediant',
            name='dose_recomm',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ingrediant',
            name='dose_recomm_metrics',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
