# Generated by Django 4.0.3 on 2022-04-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_included_dose_alter_included_dose_metrics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='included',
            name='dose',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='included',
            name='dose_metrics',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
