# Generated by Django 4.0.3 on 2022-04-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_included_dose_alter_included_dose_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediant',
            name='dose_recomm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingrediant',
            name='dose_recomm_metrics',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
