# Generated by Django 4.0.3 on 2022-04-03 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_uid'),
        ('accounts', '0005_order_order_number_order_product_order_quantity'),
    ]

    operations = [
    ]
