# Generated by Django 4.0.3 on 2022-04-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20220403_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_review',
            field=models.BooleanField(default=False),
        ),
    ]
