# Generated by Django 4.0.3 on 2022-04-04 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20220403_1908'),
        ('accounts', '0007_order_has_review'),
    ]

    operations = [
    ]
